Repository WebAudio/web-audio-api, pull requests merged in 2019-06, with the labels that each got.

#1938 Fix #1866: Remove references to garbage collection
  index.bs
Labels: Editorial/Documentation

#1939 Fix #1894: Remove text from orientationX
  index.bs
Labels: Editorial/Documentation

#1875 Apply new GC changes to AudioWorkletNode's processing condition
  index.bs
Labels: In PR Review

#1941 Fix #1893: active processing for panner/convolver/merger
  index.bs
Labels: Editorial/Documentation

#1956 Put the example for queuing a control message next to the definition of the context
  index.bs
Labels: Editorial/Documentation, In PR Review

#1962 Rewrite the convolver buffer setter steps in an algorithm, remove the connection provision from the setter
  index.bs
Labels: Editorial/Documentation

#1958 Explain why the MediaStreamAudioSourceNode has a slot
  index.bs
Labels: Editorial/Documentation, In PR Review

#1957 Update the length of the parameter sequence after #1471.
  index.bs
Labels: Editorial/Documentation

#1952 Make the Background section of Processing model non-normative.
  index.bs
Labels: Editorial/Documentation
