Repository WebAudio/web-audio-api, pull requests merged in 2019-05, with the labels that each got.

#1853 Throw in case of non-existent connection in the three-argument version of `AudioNode.disconnect`
  index.bs
Labels: V1 Blocker

#1838 Fix #1788: Clarify the value returned by the AudioParam value getter.
  index.bs
Labels: In PR Review

#1881 Address #1857: Fix typos thru AudioListener
  index.bs
Labels: Editorial/Documentation

#1887 Fix #1868: cleanup oac resume algo
  index.bs
Labels: Editorial/Documentation

#1883 Address #1857: Fix typos thru DelayNode
  index.bs
Labels: Editorial/Documentation

#1885 Fix #1880: setOrientation description
  index.bs
Labels: Editorial/Documentation

#1911 Address #1857: Fix typos/phrasing through 6. Audio Signal Values
  index.bs
Labels: Editorial/Documentation

#1926 Fix #1879: ABSN playback algorithm offset
  index.bs
Labels: Editorial/Documentation

#1895 Address #1857: Fix typos up to PeriodicWave
  index.bs
Labels: Editorial/Documentation

#1898 Address #1857: Fix typos up to WaveShaperNode
  index.bs
Labels: Editorial/Documentation

#1902 Address #1857: Fix typo/phrasing through AudioWorkletNode
  index.bs
Labels: Editorial/Documentation
